export const en = [
  {
    id: 1,
    label: "apple",
    traduction_id: 1,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 2,
    label: "dog",
    traduction_id: 2,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 3,
    label: "cat",
    traduction_id: 3,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 4,
    label: "car",
    traduction_id: 4,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 5,
    label: "house",
    traduction_id: 5,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 6,
    label: "tree",
    traduction_id: 6,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 7,
    label: "water",
    traduction_id: 7,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 8,
    label: "sun",
    traduction_id: 8,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 9,
    label: "moon",
    traduction_id: 9,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 10,
    label: "star",
    traduction_id: 10,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 11,
    label: "milk",
    traduction_id: 11,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 12,
    label: "bread",
    traduction_id: 12,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 13,
    label: "book",
    traduction_id: 13,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 14,
    label: "ball",
    traduction_id: 14,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 15,
    label: "chair",
    traduction_id: 15,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 16,
    label: "table",
    traduction_id: 16,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 17,
    label: "bird",
    traduction_id: 17,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 18,
    label: "fish",
    traduction_id: 18,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 19,
    label: "shoe",
    traduction_id: 19,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 20,
    label: "hat",
    traduction_id: 20,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 21,
    label: "banana",
    traduction_id: 21,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 22,
    label: "orange",
    traduction_id: 22,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 23,
    label: "grape",
    traduction_id: 23,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 24,
    label: "pen",
    traduction_id: 24,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 25,
    label: "pencil",
    traduction_id: 25,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 26,
    label: "school",
    traduction_id: 26,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 27,
    label: "friend",
    traduction_id: 27,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 28,
    label: "mom",
    traduction_id: 28,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 29,
    label: "dad",
    traduction_id: 29,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 30,
    label: "baby",
    traduction_id: 30,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 31,
    label: "toy",
    traduction_id: 31,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 33,
    label: "cow",
    traduction_id: 33,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 34,
    label: "pig",
    traduction_id: 34,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 35,
    label: "duck",
    traduction_id: 35,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 36,
    label: "sheep",
    traduction_id: 36,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 37,
    label: "goat",
    traduction_id: 37,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 38,
    label: "horse",
    traduction_id: 38,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 40,
    label: "juice",
    traduction_id: 40,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 41,
    label: "cookie",
    traduction_id: 41,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 42,
    label: "cake",
    traduction_id: 42,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 43,
    label: "spoon",
    traduction_id: 43,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 44,
    label: "fork",
    traduction_id: 44,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 45,
    label: "knife",
    traduction_id: 45,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 46,
    label: "plate",
    traduction_id: 46,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 47,
    label: "cup",
    traduction_id: 47,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 48,
    label: "bed",
    traduction_id: 48,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 49,
    label: "window",
    traduction_id: 49,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
  {
    id: 50,
    label: "door",
    traduction_id: 50,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "en",
  },
];