export const pt = [
  {
    id: 1,
    label: "maçã",
    traduction_id: 1,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 2,
    label: "cachorro",
    traduction_id: 2,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 3,
    label: "gato",
    traduction_id: 3,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 4,
    label: "carro",
    traduction_id: 4,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 5,
    label: "casa",
    traduction_id: 5,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 6,
    label: "árvore",
    traduction_id: 6,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 7,
    label: "água",
    traduction_id: 7,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 8,
    label: "sol",
    traduction_id: 8,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 9,
    label: "lua",
    traduction_id: 9,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 10,
    label: "estrela",
    traduction_id: 10,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 11,
    label: "leite",
    traduction_id: 11,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 12,
    label: "pão",
    traduction_id: 12,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 13,
    label: "livro",
    traduction_id: 13,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 14,
    label: "bola",
    traduction_id: 14,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 15,
    label: "cadeira",
    traduction_id: 15,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 16,
    label: "mesa",
    traduction_id: 16,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 17,
    label: "pássaro",
    traduction_id: 17,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 18,
    label: "peixe",
    traduction_id: 18,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 19,
    label: "sapato",
    traduction_id: 19,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 20,
    label: "chapéu",
    traduction_id: 20,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 21,
    label: "banana",
    traduction_id: 21,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 22,
    label: "laranja",
    traduction_id: 22,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 23,
    label: "uva",
    traduction_id: 23,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 24,
    label: "caneta",
    traduction_id: 24,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 25,
    label: "lápis",
    traduction_id: 25,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 26,
    label: "escola",
    traduction_id: 26,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 27,
    label: "amigo",
    traduction_id: 27,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 28,
    label: "mamãe",
    traduction_id: 28,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 29,
    label: "papai",
    traduction_id: 29,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 30,
    label: "bebê",
    traduction_id: 30,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 31,
    label: "brinquedo",
    traduction_id: 31,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 33,
    label: "vaca",
    traduction_id: 33,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 34,
    label: "porco",
    traduction_id: 34,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 35,
    label: "pato",
    traduction_id: 35,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 36,
    label: "ovelha",
    traduction_id: 36,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 37,
    label: "cabra",
    traduction_id: 37,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 38,
    label: "cavalo",
    traduction_id: 38,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 40,
    label: "suco",
    traduction_id: 40,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 41,
    label: "biscoito",
    traduction_id: 41,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 42,
    label: "bolo",
    traduction_id: 42,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 43,
    label: "colher",
    traduction_id: 43,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 44,
    label: "garfo",
    traduction_id: 44,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 45,
    label: "faca",
    traduction_id: 45,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 46,
    label: "prato",
    traduction_id: 46,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 47,
    label: "xícara",
    traduction_id: 47,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 48,
    label: "cama",
    traduction_id: 48,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 49,
    label: "janela",
    traduction_id: 49,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 50,
    label: "porta",
    traduction_id: 50,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
];