export const pt = [
  {
    id: 1,
    label: "maçã",
    traduction_id: 1,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 2,
    label: "cachorro",
    traduction_id: 2,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 3,
    label: "gato",
    traduction_id: 3,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 4,
    label: "carro",
    traduction_id: 4,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 5,
    label: "casa",
    traduction_id: 5,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 6,
    label: "árvore",
    traduction_id: 6,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 7,
    label: "água",
    traduction_id: 7,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 8,
    label: "sol",
    traduction_id: 8,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 9,
    label: "lua",
    traduction_id: 9,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 10,
    label: "estrela",
    traduction_id: 10,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 11,
    label: "leite",
    traduction_id: 11,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 12,
    label: "pão",
    traduction_id: 12,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 13,
    label: "livro",
    traduction_id: 13,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 14,
    label: "bola",
    traduction_id: 14,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 15,
    label: "cadeira",
    traduction_id: 15,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 16,
    label: "mesa",
    traduction_id: 16,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 17,
    label: "pássaro",
    traduction_id: 17,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 18,
    label: "peixe",
    traduction_id: 18,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 19,
    label: "sapato",
    traduction_id: 19,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 20,
    label: "chapéu",
    traduction_id: 20,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 21,
    label: "banana",
    traduction_id: 21,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 22,
    label: "laranja",
    traduction_id: 22,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 23,
    label: "uva",
    traduction_id: 23,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 24,
    label: "caneta",
    traduction_id: 24,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 25,
    label: "lápis",
    traduction_id: 25,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 26,
    label: "escola",
    traduction_id: 26,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 27,
    label: "amigo",
    traduction_id: 27,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 28,
    label: "mamãe",
    traduction_id: 28,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 29,
    label: "papai",
    traduction_id: 29,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 30,
    label: "bebê",
    traduction_id: 30,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 31,
    label: "brinquedo",
    traduction_id: 31,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 32,
    label: "leite",
    traduction_id: 32,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 33,
    label: "vaca",
    traduction_id: 33,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 34,
    label: "porco",
    traduction_id: 34,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 35,
    label: "pato",
    traduction_id: 35,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 36,
    label: "ovelha",
    traduction_id: 36,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 37,
    label: "cabra",
    traduction_id: 37,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 38,
    label: "cavalo",
    traduction_id: 38,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 39,
    label: "leite",
    traduction_id: 39,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 40,
    label: "suco",
    traduction_id: 40,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 41,
    label: "biscoito",
    traduction_id: 41,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 42,
    label: "bolo",
    traduction_id: 42,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 43,
    label: "colher",
    traduction_id: 43,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 44,
    label: "garfo",
    traduction_id: 44,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 45,
    label: "faca",
    traduction_id: 45,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 46,
    label: "prato",
    traduction_id: 46,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 47,
    label: "xícara",
    traduction_id: 47,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 48,
    label: "cama",
    traduction_id: 48,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 49,
    label: "janela",
    traduction_id: 49,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 50,
    label: "porta",
    traduction_id: 50,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 51,
    label: "papai560",
    traduction_id: 51,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 52,
    label: "banana233",
    traduction_id: 52,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 53,
    label: "porco912",
    traduction_id: 53,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 54,
    label: "água779",
    traduction_id: 54,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 55,
    label: "árvore92",
    traduction_id: 55,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 56,
    label: "vaca445",
    traduction_id: 56,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 57,
    label: "banana233408",
    traduction_id: 57,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 58,
    label: "suco767",
    traduction_id: 58,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 59,
    label: "janela964",
    traduction_id: 59,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 60,
    label: "carro110",
    traduction_id: 60,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 61,
    label: "prato702",
    traduction_id: 61,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 62,
    label: "brinquedo274",
    traduction_id: 62,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 63,
    label: "janela420",
    traduction_id: 63,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 64,
    label: "garfo138",
    traduction_id: 64,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 65,
    label: "leite190",
    traduction_id: 65,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 66,
    label: "caneta149",
    traduction_id: 66,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 67,
    label: "cama457",
    traduction_id: 67,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 68,
    label: "cabra748",
    traduction_id: 68,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 69,
    label: "pato646",
    traduction_id: 69,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 70,
    label: "escola73",
    traduction_id: 70,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 71,
    label: "papai560803",
    traduction_id: 71,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 72,
    label: "água429",
    traduction_id: 72,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 73,
    label: "árvore92581",
    traduction_id: 73,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 74,
    label: "bebê451",
    traduction_id: 74,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 75,
    label: "porco957",
    traduction_id: 75,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 76,
    label: "peixe780",
    traduction_id: 76,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 77,
    label: "árvore55",
    traduction_id: 77,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 78,
    label: "sapato380",
    traduction_id: 78,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 79,
    label: "garfo542",
    traduction_id: 79,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 80,
    label: "escola234",
    traduction_id: 80,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 81,
    label: "bebê451806",
    traduction_id: 81,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 82,
    label: "cachorro82",
    traduction_id: 82,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 83,
    label: "sapato237",
    traduction_id: 83,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 84,
    label: "porta563",
    traduction_id: 84,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 85,
    label: "colher253",
    traduction_id: 85,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 86,
    label: "banana233517",
    traduction_id: 86,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 87,
    label: "brinquedo170",
    traduction_id: 87,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 88,
    label: "árvore92581288",
    traduction_id: 88,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 89,
    label: "garfo432",
    traduction_id: 89,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 90,
    label: "vaca119",
    traduction_id: 90,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 91,
    label: "leite347",
    traduction_id: 91,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 92,
    label: "estrela364",
    traduction_id: 92,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 93,
    label: "janela964720",
    traduction_id: 93,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 94,
    label: "colher456",
    traduction_id: 94,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 95,
    label: "água162",
    traduction_id: 95,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 96,
    label: "carro110553",
    traduction_id: 96,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 97,
    label: "sapato380913",
    traduction_id: 97,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 98,
    label: "bebê451806145",
    traduction_id: 98,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 99,
    label: "árvore55995",
    traduction_id: 99,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 100,
    label: "colher253167",
    traduction_id: 100,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 101,
    label: "leite711",
    traduction_id: 101,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 102,
    label: "banana233938",
    traduction_id: 102,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 103,
    label: "árvore55159",
    traduction_id: 103,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 104,
    label: "papai990",
    traduction_id: 104,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 105,
    label: "bebê420",
    traduction_id: 105,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 106,
    label: "janela964950",
    traduction_id: 106,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 107,
    label: "banana233517284",
    traduction_id: 107,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 108,
    label: "banana233517284642",
    traduction_id: 108,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 109,
    label: "papai560308",
    traduction_id: 109,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 110,
    label: "papai466",
    traduction_id: 110,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 111,
    label: "carro110553582",
    traduction_id: 111,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 112,
    label: "garfo138128",
    traduction_id: 112,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 113,
    label: "ovelha404",
    traduction_id: 113,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 114,
    label: "papai651",
    traduction_id: 114,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 115,
    label: "banana233517284148",
    traduction_id: 115,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 116,
    label: "sapato380913732",
    traduction_id: 116,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 117,
    label: "prato702816",
    traduction_id: 117,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 118,
    label: "escola234239",
    traduction_id: 118,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 119,
    label: "garfo205",
    traduction_id: 119,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 120,
    label: "árvore92581902",
    traduction_id: 120,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 121,
    label: "cachorro82208",
    traduction_id: 121,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 122,
    label: "banana233517284642423",
    traduction_id: 122,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 123,
    label: "sapato193",
    traduction_id: 123,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 124,
    label: "sapato380935",
    traduction_id: 124,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 125,
    label: "porco912666",
    traduction_id: 125,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 126,
    label: "banana233517284148570",
    traduction_id: 126,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 127,
    label: "uva866",
    traduction_id: 127,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 128,
    label: "amigo770",
    traduction_id: 128,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 129,
    label: "biscoito755",
    traduction_id: 129,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 130,
    label: "bebê451806145446",
    traduction_id: 130,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 131,
    label: "vaca109",
    traduction_id: 131,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 132,
    label: "garfo432262",
    traduction_id: 132,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 133,
    label: "papai651916",
    traduction_id: 133,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 134,
    label: "cabra748222",
    traduction_id: 134,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 135,
    label: "banana233517284642423905",
    traduction_id: 135,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 136,
    label: "leite34789",
    traduction_id: 136,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 137,
    label: "água16297",
    traduction_id: 137,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 138,
    label: "janela964720219",
    traduction_id: 138,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 139,
    label: "cama457863",
    traduction_id: 139,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 140,
    label: "lua440",
    traduction_id: 140,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 141,
    label: "árvore92581281",
    traduction_id: 141,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 142,
    label: "banana233517284642423464",
    traduction_id: 142,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 143,
    label: "bebê451806132",
    traduction_id: 143,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 144,
    label: "cama457863668",
    traduction_id: 144,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 145,
    label: "banana233517284148570593",
    traduction_id: 145,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 146,
    label: "banana233517284642423905193",
    traduction_id: 146,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 147,
    label: "janela964950821",
    traduction_id: 147,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 148,
    label: "carro110553582156",
    traduction_id: 148,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 149,
    label: "árvore92581902259",
    traduction_id: 149,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 150,
    label: "porta563455",
    traduction_id: 150,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 151,
    label: "porta563908",
    traduction_id: 151,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 152,
    label: "escola722",
    traduction_id: 152,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 153,
    label: "porta563908241",
    traduction_id: 153,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 154,
    label: "garfo432231",
    traduction_id: 154,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 155,
    label: "ovelha614",
    traduction_id: 155,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 156,
    label: "mamãe155",
    traduction_id: 156,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 157,
    label: "garfo138926",
    traduction_id: 157,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 158,
    label: "lápis736",
    traduction_id: 158,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 159,
    label: "cachorro94",
    traduction_id: 159,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 160,
    label: "árvore92581488",
    traduction_id: 160,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 161,
    label: "carro305",
    traduction_id: 161,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 162,
    label: "sol968",
    traduction_id: 162,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 163,
    label: "cama457863668997",
    traduction_id: 163,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 164,
    label: "mesa713",
    traduction_id: 164,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 165,
    label: "janela964720219138",
    traduction_id: 165,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 166,
    label: "colher253167518",
    traduction_id: 166,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 167,
    label: "carro110553582874",
    traduction_id: 167,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 168,
    label: "banana960",
    traduction_id: 168,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 169,
    label: "brinquedo170224",
    traduction_id: 169,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 170,
    label: "banana126",
    traduction_id: 170,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 171,
    label: "árvore92581490",
    traduction_id: 171,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 172,
    label: "prato440",
    traduction_id: 172,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 173,
    label: "árvore92581902796",
    traduction_id: 173,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 174,
    label: "porco838",
    traduction_id: 174,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 175,
    label: "cachorro94508",
    traduction_id: 175,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 176,
    label: "escola722893",
    traduction_id: 176,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 177,
    label: "água16297945",
    traduction_id: 177,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 178,
    label: "árvore92581902425",
    traduction_id: 178,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 179,
    label: "porco957702",
    traduction_id: 179,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 180,
    label: "brinquedo170839",
    traduction_id: 180,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 181,
    label: "banana233408592",
    traduction_id: 181,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 182,
    label: "banana233865",
    traduction_id: 182,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 183,
    label: "leite315",
    traduction_id: 183,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 184,
    label: "leite347589",
    traduction_id: 184,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 185,
    label: "gato523",
    traduction_id: 185,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 186,
    label: "pato7",
    traduction_id: 186,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 187,
    label: "cabra294",
    traduction_id: 187,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 188,
    label: "cachorro94508933",
    traduction_id: 188,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 189,
    label: "ovelha319",
    traduction_id: 189,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 190,
    label: "lua540",
    traduction_id: 190,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 191,
    label: "cama457863732",
    traduction_id: 191,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 192,
    label: "árvore92581490536",
    traduction_id: 192,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 193,
    label: "cachorro94363",
    traduction_id: 193,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 194,
    label: "bolo216",
    traduction_id: 194,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 195,
    label: "porta563908262",
    traduction_id: 195,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 196,
    label: "brinquedo170839619",
    traduction_id: 196,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 197,
    label: "cama457863732539",
    traduction_id: 197,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 198,
    label: "cadeira722",
    traduction_id: 198,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 199,
    label: "colher117",
    traduction_id: 199,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 200,
    label: "caneta719",
    traduction_id: 200,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 201,
    label: "mamãe155338",
    traduction_id: 201,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 202,
    label: "banana233517284642423464663",
    traduction_id: 202,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 203,
    label: "bebê420372",
    traduction_id: 203,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 204,
    label: "cama457863732539831",
    traduction_id: 204,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 205,
    label: "cachorro94508811",
    traduction_id: 205,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 206,
    label: "caneta192",
    traduction_id: 206,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 207,
    label: "chapéu79",
    traduction_id: 207,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 208,
    label: "estrela46",
    traduction_id: 208,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 209,
    label: "mesa7132",
    traduction_id: 209,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 210,
    label: "garfo138883",
    traduction_id: 210,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 211,
    label: "xícara612",
    traduction_id: 211,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 212,
    label: "laranja42",
    traduction_id: 212,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 213,
    label: "vaca44556",
    traduction_id: 213,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 214,
    label: "bebê451806132241",
    traduction_id: 214,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 215,
    label: "laranja559",
    traduction_id: 215,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 216,
    label: "água16297443",
    traduction_id: 216,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 217,
    label: "cama457863731",
    traduction_id: 217,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 218,
    label: "banana233517540",
    traduction_id: 218,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 219,
    label: "mamãe155338757",
    traduction_id: 219,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 220,
    label: "prato702816955",
    traduction_id: 220,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 221,
    label: "ovelha319453",
    traduction_id: 221,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 222,
    label: "laranja42973",
    traduction_id: 222,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 223,
    label: "banana233517284642423905928",
    traduction_id: 223,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 224,
    label: "porta563908102",
    traduction_id: 224,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 225,
    label: "água779362",
    traduction_id: 225,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 226,
    label: "vaca445927",
    traduction_id: 226,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 227,
    label: "árvore92581490536790",
    traduction_id: 227,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 228,
    label: "lua54044",
    traduction_id: 228,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 229,
    label: "banana233865374",
    traduction_id: 229,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 230,
    label: "cachorro94508933313",
    traduction_id: 230,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 231,
    label: "pássaro637",
    traduction_id: 231,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 232,
    label: "garfo138128271",
    traduction_id: 232,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 233,
    label: "uva282",
    traduction_id: 233,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 234,
    label: "banana233517284642423905955",
    traduction_id: 234,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 235,
    label: "escola73950",
    traduction_id: 235,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 236,
    label: "árvore92581902259456",
    traduction_id: 236,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 237,
    label: "vaca109530",
    traduction_id: 237,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 238,
    label: "sol968118",
    traduction_id: 238,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 239,
    label: "cama457863732539831651",
    traduction_id: 239,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 240,
    label: "banana233517540606",
    traduction_id: 240,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 241,
    label: "árvore92581490536790606",
    traduction_id: 241,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 242,
    label: "cama457863732323",
    traduction_id: 242,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 243,
    label: "uva28266",
    traduction_id: 243,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 244,
    label: "pássaro499",
    traduction_id: 244,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 245,
    label: "árvore92581281618",
    traduction_id: 245,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 246,
    label: "ovelha614865",
    traduction_id: 246,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 247,
    label: "leite825",
    traduction_id: 247,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 248,
    label: "sapato380935101",
    traduction_id: 248,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 249,
    label: "porco912545",
    traduction_id: 249,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 250,
    label: "banana233517739",
    traduction_id: 250,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 251,
    label: "escola73397",
    traduction_id: 251,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 252,
    label: "árvore55159968",
    traduction_id: 252,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 253,
    label: "mesa810",
    traduction_id: 253,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 254,
    label: "banana23351728464242390519357",
    traduction_id: 254,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 255,
    label: "biscoito339",
    traduction_id: 255,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 256,
    label: "porta563908241487",
    traduction_id: 256,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 257,
    label: "mamãe15533875748",
    traduction_id: 257,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 258,
    label: "mamãe155338306",
    traduction_id: 258,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 259,
    label: "papai763",
    traduction_id: 259,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 260,
    label: "pato646665",
    traduction_id: 260,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 261,
    label: "pato646665297",
    traduction_id: 261,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 262,
    label: "casa431",
    traduction_id: 262,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 263,
    label: "pato469",
    traduction_id: 263,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 264,
    label: "mesa7132939",
    traduction_id: 264,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 265,
    label: "bebê480",
    traduction_id: 265,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 266,
    label: "mamãe155338586",
    traduction_id: 266,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 267,
    label: "escola722893554",
    traduction_id: 267,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 268,
    label: "sapato19335",
    traduction_id: 268,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 269,
    label: "árvore92581902259990",
    traduction_id: 269,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 270,
    label: "banana233408592102",
    traduction_id: 270,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 271,
    label: "bola737",
    traduction_id: 271,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 272,
    label: "sapato38091389",
    traduction_id: 272,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 273,
    label: "cadeira476",
    traduction_id: 273,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 274,
    label: "banana126597",
    traduction_id: 274,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 275,
    label: "carro460",
    traduction_id: 275,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 276,
    label: "cama457212",
    traduction_id: 276,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 277,
    label: "biscoito365",
    traduction_id: 277,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 278,
    label: "janela964950250",
    traduction_id: 278,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 279,
    label: "mamãe155338704",
    traduction_id: 279,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 280,
    label: "lua962",
    traduction_id: 280,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 281,
    label: "cama457863668893",
    traduction_id: 281,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 282,
    label: "banana233517284642423464663142",
    traduction_id: 282,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 283,
    label: "estrela467",
    traduction_id: 283,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 284,
    label: "carro110553582146",
    traduction_id: 284,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 285,
    label: "porco912666958",
    traduction_id: 285,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 286,
    label: "colher456606",
    traduction_id: 286,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 287,
    label: "biscoito767",
    traduction_id: 287,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 288,
    label: "carro110553582156178",
    traduction_id: 288,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 289,
    label: "bola577",
    traduction_id: 289,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 290,
    label: "escola722118",
    traduction_id: 290,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 291,
    label: "maçã166",
    traduction_id: 291,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 292,
    label: "pato46920",
    traduction_id: 292,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 293,
    label: "sapato380935101712",
    traduction_id: 293,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 294,
    label: "janela964950649",
    traduction_id: 294,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 295,
    label: "banana233517419",
    traduction_id: 295,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 296,
    label: "biscoito767535",
    traduction_id: 296,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 297,
    label: "suco767634",
    traduction_id: 297,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 298,
    label: "porta493",
    traduction_id: 298,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 299,
    label: "pato646192",
    traduction_id: 299,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 300,
    label: "carro460881",
    traduction_id: 300,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 301,
    label: "água77936267",
    traduction_id: 301,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 302,
    label: "maçã166454",
    traduction_id: 302,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 303,
    label: "árvore55159968888",
    traduction_id: 303,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 304,
    label: "leite32",
    traduction_id: 304,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 305,
    label: "brinquedo274361",
    traduction_id: 305,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 306,
    label: "cadeira476805",
    traduction_id: 306,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 307,
    label: "janela964950821542",
    traduction_id: 307,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 308,
    label: "garfo432262294",
    traduction_id: 308,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 309,
    label: "biscoito851",
    traduction_id: 309,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 310,
    label: "brinquedo170224153",
    traduction_id: 310,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 311,
    label: "banana233517284642423905928494",
    traduction_id: 311,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 312,
    label: "laranja559300",
    traduction_id: 312,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 313,
    label: "cama795",
    traduction_id: 313,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 314,
    label: "janela964995",
    traduction_id: 314,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 315,
    label: "bebê420934",
    traduction_id: 315,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 316,
    label: "árvore92581488195",
    traduction_id: 316,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 317,
    label: "brinquedo274361608",
    traduction_id: 317,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 318,
    label: "escola722118268",
    traduction_id: 318,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 319,
    label: "banana866",
    traduction_id: 319,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 320,
    label: "colher117666",
    traduction_id: 320,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 321,
    label: "mesa810162",
    traduction_id: 321,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 322,
    label: "banana233517284642423464547",
    traduction_id: 322,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 323,
    label: "papai367",
    traduction_id: 323,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 324,
    label: "ovelha409",
    traduction_id: 324,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 325,
    label: "brinquedo170224526",
    traduction_id: 325,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 326,
    label: "estrela46246",
    traduction_id: 326,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 327,
    label: "sapato38091373230",
    traduction_id: 327,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 328,
    label: "mamãe155338704147",
    traduction_id: 328,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 329,
    label: "porta563455661",
    traduction_id: 329,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 330,
    label: "pato7918",
    traduction_id: 330,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 331,
    label: "cama457863625",
    traduction_id: 331,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 332,
    label: "porta493847",
    traduction_id: 332,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 333,
    label: "garfo138926821",
    traduction_id: 333,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 334,
    label: "papai798",
    traduction_id: 334,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 335,
    label: "porta563908241487933",
    traduction_id: 335,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 336,
    label: "bebê451806145483",
    traduction_id: 336,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 337,
    label: "estrela680",
    traduction_id: 337,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 338,
    label: "banana233517284642423845",
    traduction_id: 338,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 339,
    label: "maçã16645427",
    traduction_id: 339,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 340,
    label: "brinquedo17083948",
    traduction_id: 340,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 341,
    label: "escola234990",
    traduction_id: 341,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 342,
    label: "água16297618",
    traduction_id: 342,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 343,
    label: "estrela46855",
    traduction_id: 343,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 344,
    label: "garfo138926821535",
    traduction_id: 344,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 345,
    label: "cama457863668893265",
    traduction_id: 345,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 346,
    label: "banana233517540606614",
    traduction_id: 346,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 347,
    label: "banana233517284642423927",
    traduction_id: 347,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 348,
    label: "cama457863625473",
    traduction_id: 348,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 349,
    label: "mamãe15533875748970",
    traduction_id: 349,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 350,
    label: "estrela460",
    traduction_id: 350,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 351,
    label: "árvore92581902796802",
    traduction_id: 351,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 352,
    label: "cabra748119",
    traduction_id: 352,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 353,
    label: "água16297898",
    traduction_id: 353,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 354,
    label: "leite711608",
    traduction_id: 354,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 355,
    label: "biscoito755422",
    traduction_id: 355,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 356,
    label: "garfo432458",
    traduction_id: 356,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 357,
    label: "sapato38091389539",
    traduction_id: 357,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 358,
    label: "cachorro82153",
    traduction_id: 358,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 359,
    label: "uva866212",
    traduction_id: 359,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 360,
    label: "garfo623",
    traduction_id: 360,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 361,
    label: "cama457863104",
    traduction_id: 361,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 362,
    label: "porco912666216",
    traduction_id: 362,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 363,
    label: "mamãe155338704147595",
    traduction_id: 363,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 364,
    label: "banana233517419826",
    traduction_id: 364,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 365,
    label: "banana233408245",
    traduction_id: 365,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 366,
    label: "porco838821",
    traduction_id: 366,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 367,
    label: "banana233517284733",
    traduction_id: 367,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 368,
    label: "carro305688",
    traduction_id: 368,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 369,
    label: "bebê420132",
    traduction_id: 369,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 370,
    label: "peixe78045",
    traduction_id: 370,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 371,
    label: "banana233517419826138",
    traduction_id: 371,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 372,
    label: "xícara427",
    traduction_id: 372,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 373,
    label: "cama457863732539831460",
    traduction_id: 373,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 374,
    label: "porco838821434",
    traduction_id: 374,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 375,
    label: "banana233517284733339",
    traduction_id: 375,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 376,
    label: "cavalo433",
    traduction_id: 376,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 377,
    label: "banana233517739787",
    traduction_id: 377,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 378,
    label: "brinquedo170771",
    traduction_id: 378,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 379,
    label: "colher253167518451",
    traduction_id: 379,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 380,
    label: "sapato380412",
    traduction_id: 380,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 381,
    label: "banana23391",
    traduction_id: 381,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 382,
    label: "pão375",
    traduction_id: 382,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 383,
    label: "árvore9258190225999025",
    traduction_id: 383,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 384,
    label: "faca650",
    traduction_id: 384,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 385,
    label: "garfo138883785",
    traduction_id: 385,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 386,
    label: "árvore92581490536412",
    traduction_id: 386,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 387,
    label: "papai560148",
    traduction_id: 387,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 388,
    label: "árvore92581490536412578",
    traduction_id: 388,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 389,
    label: "árvore92581488195376",
    traduction_id: 389,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 390,
    label: "garfo432262722",
    traduction_id: 390,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 391,
    label: "colher253167518336",
    traduction_id: 391,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 392,
    label: "biscoito767432",
    traduction_id: 392,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 393,
    label: "escola234951",
    traduction_id: 393,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 394,
    label: "janela964950912",
    traduction_id: 394,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 395,
    label: "papai560308602",
    traduction_id: 395,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 396,
    label: "pato646771",
    traduction_id: 396,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 397,
    label: "cama457863732620",
    traduction_id: 397,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 398,
    label: "vaca759",
    traduction_id: 398,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 399,
    label: "leite520",
    traduction_id: 399,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 400,
    label: "banana233517284642423464547759",
    traduction_id: 400,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 401,
    label: "pato469430",
    traduction_id: 401,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 402,
    label: "ovelha614335",
    traduction_id: 402,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 403,
    label: "banana23351773978757",
    traduction_id: 403,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 404,
    label: "porco838912",
    traduction_id: 404,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 405,
    label: "peixe780726",
    traduction_id: 405,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 406,
    label: "leite711608322",
    traduction_id: 406,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 407,
    label: "cachorro94508933313148",
    traduction_id: 407,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 408,
    label: "cama457863668893265829",
    traduction_id: 408,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 409,
    label: "colher253167518336866",
    traduction_id: 409,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 410,
    label: "carro110553582156619",
    traduction_id: 410,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 411,
    label: "garfo138926156",
    traduction_id: 411,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 412,
    label: "banana126597749",
    traduction_id: 412,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 413,
    label: "árvore92581902425903",
    traduction_id: 413,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 414,
    label: "carro110553582211",
    traduction_id: 414,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 415,
    label: "árvore92581902266",
    traduction_id: 415,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 416,
    label: "porco912999",
    traduction_id: 416,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 417,
    label: "porta563908102400",
    traduction_id: 417,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 418,
    label: "biscoito767535603",
    traduction_id: 418,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 419,
    label: "maçã394",
    traduction_id: 419,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 420,
    label: "porco912666408",
    traduction_id: 420,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 421,
    label: "cabra913",
    traduction_id: 421,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 422,
    label: "cama795217",
    traduction_id: 422,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 423,
    label: "chapéu604",
    traduction_id: 423,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 424,
    label: "cama457863668551",
    traduction_id: 424,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 425,
    label: "prato702717",
    traduction_id: 425,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 426,
    label: "lua540211",
    traduction_id: 426,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 427,
    label: "cama795995",
    traduction_id: 427,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 428,
    label: "banana126756",
    traduction_id: 428,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 429,
    label: "papai721",
    traduction_id: 429,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 430,
    label: "lápis655",
    traduction_id: 430,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 431,
    label: "bola880",
    traduction_id: 431,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 432,
    label: "banana233517284642423845289",
    traduction_id: 432,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 433,
    label: "sapato38091373230838",
    traduction_id: 433,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 434,
    label: "janela299",
    traduction_id: 434,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 435,
    label: "porta563908241487153",
    traduction_id: 435,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 436,
    label: "sapato38091389539159",
    traduction_id: 436,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 437,
    label: "maçã166128",
    traduction_id: 437,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 438,
    label: "árvore92581490536412367",
    traduction_id: 438,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 439,
    label: "papai466101",
    traduction_id: 439,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 440,
    label: "brinquedo782",
    traduction_id: 440,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 441,
    label: "biscoito76753544",
    traduction_id: 441,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 442,
    label: "estrela680726",
    traduction_id: 442,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 443,
    label: "cachorro94508933604",
    traduction_id: 443,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 444,
    label: "sapato19335651",
    traduction_id: 444,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 445,
    label: "colher456606105",
    traduction_id: 445,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 446,
    label: "estrela460546",
    traduction_id: 446,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 447,
    label: "maçã166128864",
    traduction_id: 447,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 448,
    label: "pássaro499189",
    traduction_id: 448,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 449,
    label: "banana866875",
    traduction_id: 449,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 450,
    label: "lua540784",
    traduction_id: 450,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 451,
    label: "caneta719976",
    traduction_id: 451,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 452,
    label: "estrela868",
    traduction_id: 452,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 453,
    label: "banana23391961",
    traduction_id: 453,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 454,
    label: "pato469975",
    traduction_id: 454,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 455,
    label: "pato646665922",
    traduction_id: 455,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 456,
    label: "carro110553582146982",
    traduction_id: 456,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 457,
    label: "ovelha409851",
    traduction_id: 457,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 458,
    label: "mesa7132757",
    traduction_id: 458,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 459,
    label: "estrela467921",
    traduction_id: 459,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 460,
    label: "árvore92581281230",
    traduction_id: 460,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 461,
    label: "prato702816292",
    traduction_id: 461,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 462,
    label: "pato646771484",
    traduction_id: 462,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 463,
    label: "leite347589293",
    traduction_id: 463,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 464,
    label: "carro110553582146974",
    traduction_id: 464,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 465,
    label: "lua440646",
    traduction_id: 465,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 466,
    label: "mesa81016217",
    traduction_id: 466,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 467,
    label: "sapato380935101703",
    traduction_id: 467,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 468,
    label: "bebê420934785",
    traduction_id: 468,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 469,
    label: "banana23351728464242390519357736",
    traduction_id: 469,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 470,
    label: "escola73493",
    traduction_id: 470,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 471,
    label: "árvore92581288783",
    traduction_id: 471,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 472,
    label: "mamãe155338704344",
    traduction_id: 472,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 473,
    label: "cachorro94508933313148831",
    traduction_id: 473,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 474,
    label: "banana2335172846424234645477597",
    traduction_id: 474,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 475,
    label: "leite711608322963",
    traduction_id: 475,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 476,
    label: "sapato380935101826",
    traduction_id: 476,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 477,
    label: "pato46920705",
    traduction_id: 477,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 478,
    label: "sol968118257",
    traduction_id: 478,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 479,
    label: "bebê683",
    traduction_id: 479,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 480,
    label: "porta563908241487482",
    traduction_id: 480,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 481,
    label: "ovelha614865673",
    traduction_id: 481,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 482,
    label: "biscoito767535603716",
    traduction_id: 482,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 483,
    label: "faca539",
    traduction_id: 483,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 484,
    label: "janela964950250984",
    traduction_id: 484,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 485,
    label: "mamãe155338213",
    traduction_id: 485,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 486,
    label: "cama457863731988",
    traduction_id: 486,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 487,
    label: "pássaro847",
    traduction_id: 487,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 488,
    label: "peixe780726303",
    traduction_id: 488,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 489,
    label: "banana23351728464242390592841",
    traduction_id: 489,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 490,
    label: "garfo138236",
    traduction_id: 490,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 491,
    label: "bebê451806145131",
    traduction_id: 491,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 492,
    label: "água16297132",
    traduction_id: 492,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 493,
    label: "caneta238",
    traduction_id: 493,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 494,
    label: "banana126268",
    traduction_id: 494,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 495,
    label: "bebê451806145446429",
    traduction_id: 495,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 496,
    label: "janela420789",
    traduction_id: 496,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 497,
    label: "bola577208",
    traduction_id: 497,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 498,
    label: "caneta71975",
    traduction_id: 498,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 499,
    label: "bebê480249",
    traduction_id: 499,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
  {
    id: 500,
    label: "colher253167518451848",
    traduction_id: 500,
    matched: false,
    error: false,
    selected: false,
    used: false,
    disabled: false,
    lang: "pt",
  },
];
